name: Kernel_action


on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-20.04


    steps:

      - uses: actions/checkout@v2


      - name: Git kernel
        run: |
          git clone https://github.com/Gainss/kernel_xiaomi_cepheus -b eleven

      - name: Make kernel
        run: |
          cd $GITHUB_WORKSPACE/kernel_xiaomi_cepheus && bash ./build.sh

      - name: Upload to Release‌‌...
        uses: ncipollo/release-action@v1.8.0
        with:
           files: $GITHUB_WORKSPACE/android_kernel_oneplus_msm899/out/arch/arm64/boot
           name: Image.gz-dtb
           tag_name: main
