name: Kernel_action


on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-20.04


    steps:

      - uses: actions/checkout@v2

      - name: setup
        run: |
          git clone --depth=1 https://gitlab.com/jjpprrrr/prelude-clang.git $CLANG_PATH
          sh -c "$(curl -sSL https://github.com/akhilnarang/scripts/raw/master/setup/android_build_env.sh/)"


      - name: Git kernel
        run: |
          git clone https://github.com/Gainss/kernel_xiaomi_cepheus -b eleven kernel
          

      - name: clean
        run: |
          cd $GITHUB_WORKSPACE/kernel
          rm -rf $KERNEL_PATH/out/ *.zip
          make mrproper && git reset --hard HEAD

      - name: Make kernel
        run: |
          bash ./build.sh

      - name: Upload to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "kernel/out/arch/arm64/boot/Image.gz-dtb"
          tag: "test"
          token: ${{ secrets.GITHUB_TOKEN }}
