name: Kernel_action


on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-20.04


    steps:

      - uses: actions/checkout@v2


      - name: Git kernel
        run: |
          git clone https://github.com/PixelExperience-Devices/kernel_xiaomi_cepheus -b eleven kernel
          


      - name: Make kernel
        run: |
          cd $GITHUB_WORKSPACE/kernel && bash ./build.sh

      - name: Upload to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "kernel/out/arch/arm64/boot/Image.gz-dtb"
          tag: "test v1"
          token: ${{ secrets.GITHUB_TOKEN }}
